export interface Location {
  latitude: number;
  longitude: number;
}
export interface NewUsuario {
  nombre: string;
  apellido: string;
  email: string;
  password: string;
  rePassword: string;
}

export interface UsuarioToken {
  usuario: Usuario;
  token: string;
}

export interface Login {
  email: string;
  password: string;
}

// Generated by https://quicktype.io

export interface Usuario {
  id: string;
  nombre: string;
  apellido: string;
  email: string;
  photo?: string;
  google?: boolean;
}
